### ISSUE TITLE
MEASUR: Custom Materials bugs/improvements

### ISSUE THREAD

**Issue by JL102** [ORNL-AMO/AMO-Tools-Desktop#5740]
Related to #3542

Issues to create
1. [x] Don't make the "Add" button disappear when you click the dropdown if no materials for that category exist
2. [x] Dropdown carets (v and ^) point in the wrong direction on both Custom Materials and Settings
    a. They're also positioned slightly too high and too far to the right edge
3. [x] If "Select all folder content" is checked, adding a new material should auto-check it
4. [x] #5681 
5. [x] Floating point issues in display: Create solid/liquid and set any of the parameters to 1.8%. Results in 1.8000000000000003% when you preview it (Doesn't happen for any other)
6. [x] Horizonal Scroll bar exists when it shouldn't

**Comment by nbintertech** [comment]
As discussed in Slack, drop " Share Import/Export module with Assessments" please

**Comment by JL102** [comment]
MB, forgot about that when I pasted the list in
